### ISSUE TITLE
Pomoč

### ISSUE THREAD

**Issue by TjasaKosenina** [TjasaKosenina/olimpijske-igre#1]
Napako v primeru, da nimava prvouvrščenega sva rešili s stavkom elif v tekstovnem vmesniku v funkciji prikazi_prvouvrscene_v_disciplini():.
Pojavi se nama nova napaka v primeru, da imava prvouvrščenega (npr. pri 100m delfin):
Vnesite izbiro > 3
Vnesite disciplino: 100m delfin
Traceback (most recent call last):
  File ".\teksovni_vmesnik.py", line 123, in <module>
    main()
  File ".\teksovni_vmesnik.py", line 120, in main
    pokazi_moznosti()
  File ".\teksovni_vmesnik.py", line 106, in pokazi_moznosti
    prikazi_prvouvrscene_v_disciplini()
  File ".\teksovni_vmesnik.py", line 86, in prikazi_prvouvrscene_v_disciplini
    ime, priimek, leto = modeli.podatki_disciplina(kljuc_disciplina)
ValueError: not enough values to unpack (expected 3, got 1)
Prosiva za pomoč. Hvala.

**Comment by jaanos** [comment]
Kot sem vama že napisal, bo potrebno z zanko `for` čez seznam. Glede na to, da preverjata, ali je ta prazen, si ga lahko shranita v spremenljivko (in tako poizvedbe ne delata dvakrat), npr.
```python
def prikazi_prvouvrscene_v_disciplini():
    kljuc_disciplina = izberi_disciplino()
    if kljuc_disciplina is None:
        print('Disciplina ne obstaja.')
    else:
        zmagovalci = modeli.podatki_disciplina(kljuc_disciplina)
        if len(zmagovalci) == 0:
            print('V tej disciplini ni prvouvrščenih.')
        else:
            for ime, priimek, leto in zmagovalci:
                print('{} {} {}'.format(ime, priimek, leto))
```

Še to: da v issueju lepo prikažeta kodo, naredita tako:

~~~
```python
koda
```
~~~

Oznaka `python` pomeni, da je koda v Pythonu in se bo potem ustrezno pobarvala (po potrebi lahko seveda uporabita tudi druge programske jezike, npr. `SQL` - ali pa izpustita, pa se koda ne bo pobarvala). S klikom na *View* lahko pred objavo vidita, kako bo ta izgledala.

**Comment by TjasaKosenina** [comment]
Hvala. Nama je uspelo odpraviti napako.
