### ISSUE TITLE
tekstovni vmesnik

### ISSUE THREAD

**Issue by TjasaKosenina** [TjasaKosenina/olimpijske-igre#2]
Prosile bi za pomoč pri tekstovnem vmesniku. Opazile sva, da nama ne dela prva točka Prikaži podatke olimpijskih iger. To nama je že delalo, vendar sedaj po popravkih za spletni vmesnik ne dela več. Hvala za pomoč.

**Comment by jaanos** [comment]
Očitno sta spremenili, kako deluje funkcija `modeli.poisci_olimpijske` - ta naj bi vračala samo ključ za olimpijske igre, če te obstajajo. Tako lahko v funkciji `tekstovni_vmesnik.izberi_olimpijske` enostavno vrneta `modeli.poisci_olimpijske(niz)`, saj bo to že prava vrednost.

Problem se sicer pojavi v `modeli.poisci_olimpijske`, če za podano leto ni bilo olimpijskih iger, saj v tem primeru poskusita vrednost izluščiti iz `None`. Svetujem, da naredita tako:
```python
    indeks = conn.execute(poizvedba, [letoPodano]).fetchone()
    if indeks is not None:
        indeks, = indeks
    return indeks
```
Tako bo funkcija vrnila `None`, če olimpijskih iger ne najde (kar ustreza temu, kar pričakuje `tekstovni_vmesnik.prikazi_podatke_OI`), oziroma ustrezen indeks, če so v bazi.

**Comment by UrsaKl** [comment]
Hvala za pomoč! Napako nama je uspelo odpraviti!
